<?php

namespace ContainerFkH8R2q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FMzUZQZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FMzUZQZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FMzUZQZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'requests' => ['privates', '.errored.Q8QkPWV', NULL, 'Cannot determine controller argument for "App\\Controller\\CustomerController::createProduct()": the $requests argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'doctrine' => '?',
            'requests' => '?',
        ]);
    }
}
