<?php

namespace ContainerRD1rU9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VllnoGnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vllnoGn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vllnoGn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'request' => ['privates', '.errored.23WRYg5', NULL, 'Cannot determine controller argument for "App\\Controller\\CustomerController::update()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'doctrine' => '?',
            'request' => '?',
        ]);
    }
}
