controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
customer_show:
    path: /customer/show/{id}
    controller: App\Controller\CustomerController::show
customer_update:
    path: /customer/update/{id}
    controller: App\Controller\CustomerController::update
customer_create_view:
    path: /customer/showCreate
    controller: App\Controller\CustomerController::showCreate
customer_create:
    path: /customer/create
    controller: App\Controller\CustomerController::create


