controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
customer_show:
    path: /customer/show/{id}
    controller: App\Controller\CustomerController::show



