controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
customer_show:
    path: /customer/show/{id}
    controller: App\Controller\CustomerController::show
customer_update:
    path: /customer/update/{id}
    controller: App\Controller\CustomerController::update_customer
customer_create_view:
    path: /customer/showCreate
    controller: App\Controller\CustomerController::showCreate
customer_create:
    path: /customer/create
    controller: App\Controller\CustomerController::createProduct
customer_delete:
    path: /customer/delete/{id}
    controller: App\Controller\CustomerController::delete_customer
customer_upload_file:
    path: /customer/upload_file
    controller: App\Controller\CustomerController::upload_file
customer_update_byemail:
    path: /customer/customer_update_byemail/
    controller: App\Controller\CustomerController::updateByEmail
customer_create_byemail:
    path: /customer/customer_create_byemail
    controller: App\Controller\CustomerController::createByEmail


