<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFkH8R2q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFkH8R2q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFkH8R2q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFkH8R2q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFkH8R2q\App_KernelDevDebugContainer([
    'container.build_hash' => 'FkH8R2q',
    'container.build_id' => '281ea313',
    'container.build_time' => 1645435260,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFkH8R2q');
