<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTeqEuKR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTeqEuKR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTeqEuKR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTeqEuKR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTeqEuKR\App_KernelDevDebugContainer([
    'container.build_hash' => 'TeqEuKR',
    'container.build_id' => '5d287337',
    'container.build_time' => 1645284254,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTeqEuKR');
